version: "3.7"
services:
  app:
    build:
      args:
        user: ${APP_NAME}-user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: ${APP_NAME}-img
    container_name: ${APP_NAME}-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www:delegated
      - ./logs:/var/logs:delegated
    networks:
      - pim-network

  db:
    image: mongo:latest
    container_name: ${APP_NAME}-db
    restart: unless-stopped
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
        MONGO_INITDB_DATABASE: ${DB_DATABASE}
    volumes:
        - ./data:/data/db:delegated
    networks: 
        - pim-network

  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME}-nginx
    restart: unless-stopped
    ports:
      - 8001:80
    volumes:
      - ./:/var/www:cached
      - ./docker-compose/nginx:/etc/nginx/conf.d/:cached
    networks:
      - pim-network

networks:
  pim-network:
    driver: bridge